# Site settings
title: Richard Li
description: About Richard Li - A portfolio showcasing various projects
baseurl: ""
url: "https://richardhcli.github.io"
author: Richard Li

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  pages:
    output: true
    permalink: /:name/
  project_posts:
    output: true
    permalink: /projects/:name/
  blog_posts:
    output: true
    permalink: /blog/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "project/_posts"
      type: "project_posts"
    values:
      layout: "projectPost"
  - scope:
      path: "blog/_posts"
      type: "blog_posts"
    values:
      layout: "blogPost"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
